#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env["mcp"]:
    env.add_source_files(env.scene_sources, "*.cpp")
else:
    debugger_sources = [source for source in env.Glob("*.cpp") if not source.name.startswith("mcp_runtime_")]
    env.add_source_files(env.scene_sources, debugger_sources)
